### ISSUE TITLE
How To Install?

### ISSUE THREAD

**Issue by leo2r** [mbaske/grid-sensor#11]
Hi,

I'm really looking forward to playing around with your grid-sensor! However, I'm new to Unity and I'm not sure how to install your component extension for it to work with ml-agents? I looked through your documentation but there doesn't seem to be an installation guide 😅 Could you give me a few pointers please? 

Thank you!

**Comment by mbaske** [comment]
Hi, thanks for checking out my sensor! If you just want to see it in action, you can simply clone the repo, open the project in Unity and run a demo scene. Dependencies should load automatically. However, if you'd like to train agents, you'll need to install the python backend for ml-agents. Here's an installation guide https://virajvaitha.medium.com/unity-ml-agents-2022-installation-e8af1eab2dd

**Comment by leo2r** [comment]
Hi, thanks for the quick reply! I've already installed the python backend and trained my agent. I mean how do I use your sensor in my project? Do I just manually add the manifest.json file from your Packages folder? Or how would I do it? Thank you! :D

**Comment by mbaske** [comment]
You only need to add the line
`com.dbrizov.naughtyattributes": "https://github.com/dbrizov/NaughtyAttributes.git#upm",`
to the dependencies in your manifest.json
Other than that, just copy the `Scripts` folder from my repo.

**Comment by leo2r** [comment]
Great, thank you so much! :D
