### ISSUE TITLE
2D Grid Sensor for XY axis

### ISSUE THREAD

**Issue by SandaruwanFdo** [mbaske/grid-sensor#13]
![image](https://user-images.githubusercontent.com/5012179/186487886-4c54ac33-d213-4d1e-ab41-7e46b2830d3b.png)

How to set 2D grid sensor for XY axis?

**Comment by mbaske** [comment]
Hi, you can try rotating your agent gameobject by 90 degrees and set the sensor `Rotation Type` to `Agent XYZ`.

**Comment by SandaruwanFdo** [comment]
Got it. Thank you
