### ISSUE TITLE
2D Grid Sensor Write Out of Bounds Error

### ISSUE THREAD

**Issue by apanay20** [mbaske/grid-sensor#15]
![image](https://user-images.githubusercontent.com/55096402/200627547-6d12039d-4b9b-42b7-8535-7ebf5728c365.png)

Hello. I get this error when using the 2D grid sensor.
I also tried ml-agents version 2.1 as you suggest but getting the same error.

**Comment by simon13372** [comment]
Had the same issue but alleviated that by changing
        public Vector2Int NormalizedToGridPos(Vector2 norm)
        {
            return new Vector2Int(
                (int)(norm.x * Width),
                (int)(norm.y * Height)
            );
        }
to

        public Vector2Int NormalizedToGridPos(Vector2 norm)
        {
            return new Vector2Int(
                (int)(norm.x * (Width - 1)),
                (int)(norm.y * (Height - 1))
            );
        }

in GridBuffer.cs

**Comment by simon13372** [comment]
Had the same problem but alleviated that by changing

public Vector2Int NormalizedToGridPos(Vector2 norm)
{
    return new Vector2Int(
        (int)(norm.x * Width),
        (int)(norm.y * Height)
    );
}

to

public Vector2Int NormalizedToGridPos(Vector2 norm)
{
    return new Vector2Int(
        (int)(norm.x * (Width - 1)),
        (int)(norm.y * (Height - 1))
    );
}

in GridBuffer.cs

**Comment by apanay20** [comment]
Thanks Simon!
