### ISSUE TITLE
Plans to update for MLAgents 3.0?

### ISSUE THREAD

**Issue by victornor** [mbaske/grid-sensor#19]
Hey, I'm considering trying your grid sensor, because the built-in grid-sensor has quite poor performance.
Are there any plans to update for MLAgents 3.0? Unity crashes whenever i run any of the example scenes with 3.0.

If not, i will attempt to make it work with 3.0.

**Comment by mbaske** [comment]
HI, I'm not planning any updates for the sensor. I haven't really kept up with the development of ml-agents during the past two years or so. Therefore I'm not sure what the points of incompatibility are with version 3.
