### ISSUE TITLE
The 2D Grid Sensor

### ISSUE THREAD

**Issue by ditlevjoergensen** [mbaske/grid-sensor#3]
Hey!

Awesome project you have set up here!

However i reaaally, miss that i can't use it in my 2D project (with axis x and y). The 2D grid sensor only works with X and Z. Im not sure why this is hardcoded, and cannot be changed. As there really shouldnt be any difference between using X and Y?

Hope you will look into adding this :)

Regards!

**Comment by mbaske** [comment]
Thanks for your feedback @ditlevjoergensen!
I have to admit that I've hardly worked with 2D Unity projects yet. Unfortunatly, this isn't just an issue with the axes. My code for parsing point positions was designed for 3D and the physics methods for detecting colliders would also be different for 2D. I might look into generalizing the sensor even more at some point, but haven't set a timeline yet.

**Comment by ditlevjoergensen** [comment]
Ahh i see! Because i was thinking of just changeing all the z and y staff around myself. But if that wont work anyway i might need to start from the beginning :) 

But TY for coming this feature, from what i have played around with it, its really intuitive.
