### ISSUE TITLE
'GameObjectShape.RequireScanEvent': event must be of a delegate type

### ISSUE THREAD

**Issue by MarkTensenSgt** [mbaske/grid-sensor#8]
Hi!
Im trying to use this for release 18 and copied all files from the Sensors/ folder into my project, and added NaughtyAttributes to my manifest.json, but I'm getting some errors:

`Sensors\Grid\GameObject\Detection\GameObjectShape.cs(18,29): error CS0066: 'GameObjectShape.RequireScanEvent': event must be of a delegate type`
`Sensors\Grid\Basic\Sensor\GridSensor.cs(17,29): error CS0066: 'GridSensor.UpdateEvent': event must be of a delegate type`
`Sensors\Grid\Basic\Sensor\GridSensor.cs(22,29): error CS0066: 'GridSensor.ResetEvent': event must be of a delegate type`

What could be causing this?
I'm running on Unity 2020.3.14, and using ml agents release 18

**Comment by mbaske** [comment]
Hi, this might be a dependency issue, but I'm not sure what's causing it. Can you open the repo project as is without errors? Opening it with a fresh 2020.3 install looks fine over here.

**Comment by MarkTensenSgt** [comment]
Hmmm Yes this was an interesting problem. 
Thanks for pointing to opening it as is instead of importing. It opens without errors. 
Turns out I had a class called Action in my other scripts, which was the issue. Renaming this made it work. I should work more with namescopes I guess:).

Also, great work on this repo!
