### ISSUE TITLE
write multiple sensorbuffers to multiple gridsensors on one agent?

### ISSUE THREAD

**Issue by MarkTension** [mbaske/grid-sensor#9]
Hi! 
I'm successfully implementing a single gridsensor, as implemented at the maze agent example.
For my custom agent I need more than one gridsensor. It is not entirely clear to me how to implment that correctly. 

I'm seeing that simply adding multiple gridsensor components to the agent and making multiple sensorbuffers does not work.
I've tried that in the debugging view (which is very useful), but see that only one sensor gets the input written to the sensorbuffer.

What would be a good way to implement multiple sensorbuffers to multiple gridsensors for one agent?
Thanks!

**Comment by mbaske** [comment]
Please try adding the sensor components to child game objects of your agent.

**Comment by MarkTension** [comment]
Thx! This resolved my issue. 
For anyone else going through this: I had to additionally add a script as component to each child-gameobject sensor. This script instantiates a ColorGridBuffer on the agent's Initialization, and the Write() function would be called on that ColorGridBuffer from the agent
